# Generated by Django 5.2.12 on 2026-07-27 21:01

import backend.djangoapi.managers.user
import backend.djangoapi.utils.helpers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            (
                                "STATIC_DRAWDOWN_AFTER_PAYOUT",
                                "Static drawdown after payout",
                            )
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("username", models.CharField(blank=True, max_length=50, unique=True)),
                ("birth_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("preferred_currency", models.CharField(default="USD", max_length=3)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="USD -> preferred_currency rate",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "conversion_last_updated",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", backend.djangoapi.managers.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("instrument", models.CharField(max_length=10)),
                (
                    "risk",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("contracts", models.IntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(max_length=1000)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=backend.djangoapi.utils.helpers.journal_entries_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eval_risk",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("eval_contracts", models.IntegerField(blank=True, null=True)),
                (
                    "eval_outcome",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="journal_entries", to="djangoapi.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_time"],
            },
        ),
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=150)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "baseline_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payout_date", models.DateTimeField()),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("trading_days_in_cycle", models.IntegerField(default=0)),
                (
                    "total_pnl_in_cycle",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payouts",
                        to="djangoapi.journalentry",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="djangoapi.tradingaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingAccountTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("firm", models.CharField(max_length=100)),
                ("account_size", models.IntegerField()),
                ("is_evaluation", models.BooleanField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apex", "Apex"),
                            ("myfundedfutures", "MyFundedFutures"),
                            ("topstep", "Topstep"),
                            ("ftmo", "FTMO"),
                            ("bulenox", "Bulenox"),
                            ("alpha", "alpha"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=backend.djangoapi.utils.helpers.trading_account_templates_upload_to,
                    ),
                ),
                (
                    "profit_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "profit_split",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "min_buffer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("min_trading_days", models.IntegerField(blank=True, null=True)),
                (
                    "min_day_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_drawdown", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "consistency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage (e.g. 50 for 50%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "min_payout_request",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum payout amount required to request payout",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_payout_request",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum payout allowed per request",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "withdrawal_split",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of profit that can be withdrawn (e.g. 50 for 50%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True, related_name="templates", to="djangoapi.rule"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_account_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="djangoapi.tradingaccounttemplate",
            ),
        ),
        migrations.CreateModel(
            name="TradingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_number", models.IntegerField(blank=True, null=True)),
                ("is_valid_day", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_days",
                        to="djangoapi.tradingaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="djangoapi.journalentry",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="djangoapi.payout",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="djangoapi.tradingaccount",
                    ),
                ),
                (
                    "trading_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="djangoapi.tradingday",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_tag_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "date_time"], name="djangoapi_j_user_id_1f0ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingaccounttemplate",
            index=models.Index(fields=["user"], name="djangoapi_t_user_id_f5aaca_idx"),
        ),
        migrations.AddConstraint(
            model_name="tradingaccounttemplate",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_template_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingday",
            index=models.Index(
                fields=["account", "date"], name="djangoapi_t_account_2f0168_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tradingday",
            constraint=models.UniqueConstraint(
                fields=("account", "date"), name="unique_date_per_account"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["account", "date_time"], name="djangoapi_t_account_d0177f_idx"
            ),
        ),
    ]
