# Generated by Django 5.2.12 on 2026-08-03 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apex", "Apex"),
                            ("myfundedfutures", "MyFundedFutures"),
                            ("topstep", "Topstep"),
                            ("ftmo", "FTMO"),
                            ("bulenox", "Bulenox"),
                            ("alpha", "alpha"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "account_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date"],
                "indexes": [
                    models.Index(fields=["user"], name="djangoapi_b_user_id_b8148c_idx")
                ],
            },
        ),
    ]
