# Generated by Django 6.0 on 2026-03-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0002_alter_user_managers_resetpasswordsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
