# Generated by Django 5.2.12 on 2026-04-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoapi", "0002_user_is_demo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resetpasswordsession",
            name="token",
        ),
        migrations.RemoveField(
            model_name="resetpasswordsession",
            name="verified_token",
        ),
        migrations.AddField(
            model_name="resetpasswordsession",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resetpasswordsession",
            name="token_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trading_account_templates",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resetpasswordsession",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
