# Generated by Django 6.0 on 2026-03-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0003_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAccountTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("firm", models.CharField(max_length=100)),
                ("account_size", models.IntegerField()),
                ("is_evaluation", models.BooleanField()),
                (
                    "profit_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_buffer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("min_trading_days", models.IntegerField(default=0)),
                (
                    "min_day_pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=150)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="djangoapi.tradingaccounttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("entry_time", models.TimeField()),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.URLField(blank=True, null=True)),
                ("day_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_days",
                        to="djangoapi.tradingaccount",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "entry_time"],
                        name="djangoapi_t_account_b04482_idx",
                    )
                ],
                "unique_together": {("account", "entry_time")},
            },
        ),
    ]
