# Generated by Django 5.2.12 on 2026-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0003_remove_resetpasswordsession_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-date_time"]},
        ),
        migrations.AlterModelOptions(
            name="tradingaccount",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tradingaccounttemplate",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="tradingday",
            options={"ordering": ["day_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="tradingday",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="tradingaccounttemplate",
            index=models.Index(fields=["user"], name="djangoapi_t_user_id_f5aaca_idx"),
        ),
        migrations.AddConstraint(
            model_name="tradingaccounttemplate",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_template_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="tradingday",
            constraint=models.UniqueConstraint(
                fields=("account", "day_number"), name="unique_day_number_per_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="tradingday",
            constraint=models.UniqueConstraint(
                fields=("account", "date"), name="unique_date_per_account"
            ),
        ),
    ]
