# Generated by Django 6.0 on 2026-03-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0004_tradingaccounttemplate_tradingaccount_tradingday"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("instrument", models.CharField(max_length=10)),
                ("risk", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contracts", models.IntegerField()),
                ("outcome", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(max_length=1000)),
                ("image", models.URLField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="tradingday",
            name="djangoapi_t_account_b04482_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tradingday",
            unique_together={("account", "day_number")},
        ),
        migrations.AddIndex(
            model_name="tradingday",
            index=models.Index(
                fields=["account", "date"], name="djangoapi_t_account_2f0168_idx"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="djangoapi.tradingaccount",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="trades",
            field=models.ManyToManyField(
                related_name="journal_entries", to="djangoapi.trade"
            ),
        ),
        migrations.RemoveField(
            model_name="tradingday",
            name="entry_time",
        ),
        migrations.RemoveField(
            model_name="tradingday",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tradingday",
            name="pnl",
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["account", "date_time"], name="djangoapi_t_account_d0177f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "date_time"], name="djangoapi_j_user_id_1f0ffd_idx"
            ),
        ),
    ]
