# Generated by Django 6.0 on 2026-03-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0005_journalentry_trade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_trades",
                to="djangoapi.journalentry",
            ),
        ),
    ]
