# Generated by Django 5.2.12 on 2026-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0005_remove_user_verification_token_user_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="allowable_payout_request",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Max % or amount allowed for payout request",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="consistency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage (e.g. 50 for 50%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="max_drawdown",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="profit_split",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tradingaccounttemplate",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="trading_account_templates/"
            ),
        ),
    ]
