# Generated by Django 5.2.12 on 2026-04-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0006_tradingaccounttemplate_allowable_payout_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingaccounttemplate",
            name="max_drawdown",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tradingaccounttemplate",
            name="min_trading_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
