# Generated by Django 6.0 on 2026-03-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0006_trade_journal_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="trades",
        ),
        migrations.AlterField(
            model_name="trade",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="djangoapi.journalentry",
            ),
        ),
    ]
