# Generated by Django 5.2.12 on 2026-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0007_alter_tradingaccounttemplate_max_drawdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apex", "Apex"),
                    ("myfundedfutures", "MyFundedFutures"),
                    ("topstep", "Topstep"),
                    ("ftmo", "FTMO"),
                    ("bulenox", "Bulenox"),
                    ("alpha", "alpha"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
