# Generated by Django 6.0 on 2026-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0007_remove_journalentry_trades_alter_trade_journal_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verified",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
