# Generated by Django 6.0 on 2026-03-25 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0008_remove_user_verified_user_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whop_membership_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
