# Generated by Django 5.2.12 on 2026-04-07 20:29

import backend.djangoapi.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0008_tradingaccounttemplate_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="tags",
        ),
        migrations.AlterField(
            model_name="tradingaccounttemplate",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.djangoapi.utils.helpers.upload_to,
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uses", models.IntegerField(default=0)),
            ],
            options={
                "unique_together": {("name",)},
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="journal_entries", to="djangoapi.tag"
            ),
        ),
    ]
