# Generated by Django 5.2.12 on 2026-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0010_alter_tag_unique_together_tag_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tradingday",
            name="unique_day_number_per_account",
        ),
        migrations.AddField(
            model_name="tradingday",
            name="is_valid_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tradingday",
            name="pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
