# Generated by Django 6.0 on 2026-03-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0010_emailpreferences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailpreferences",
            old_name="promotions",
            new_name="promotional_offers",
        ),
    ]
