# Generated by Django 5.2.12 on 2026-04-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0011_remove_tradingday_unique_day_number_per_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            (
                                "STATIC_DRAWDOWN_AFTER_PAYOUT",
                                "Static drawdown after payout",
                            )
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="rules",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to="djangoapi.rule"
            ),
        ),
    ]
