# Generated by Django 5.2.12 on 2026-04-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0012_rule_tradingaccounttemplate_rules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingday",
            name="pnl",
        ),
        migrations.AddField(
            model_name="trade",
            name="trading_day",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="djangoapi.tradingday",
            ),
            preserve_default=False,
        ),
    ]
