# Generated by Django 5.2.12 on 2026-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0013_remove_tradingday_pnl_trade_trading_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingday",
            name="day_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
