# Generated by Django 5.2.12 on 2026-04-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0014_alter_tradingday_day_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccount",
            name="baseline_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
