# Generated by Django 5.2.12 on 2026-04-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0015_tradingaccount_baseline_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingaccounttemplate",
            name="allowable_payout_request",
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="max_payout_request",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum payout allowed per request",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="min_payout_request",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum payout amount required to request payout",
                max_digits=10,
                null=True,
            ),
        ),
    ]
