# Generated by Django 5.2.12 on 2026-04-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoapi",
            "0016_remove_tradingaccounttemplate_allowable_payout_request_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccounttemplate",
            name="withdrawal_split",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of profit that can be withdrawn (e.g. 50 for 50%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
