# Generated by Django 5.2.12 on 2026-04-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0017_tradingaccounttemplate_withdrawal_split"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradingday",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="trade",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="djangoapi.journalentry",
            ),
        ),
    ]
