# Generated by Django 5.2.12 on 2026-04-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0018_alter_tradingday_options_alter_trade_journal_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
