# Generated by Django 5.2.12 on 2026-04-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0020_payout_trade_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payouts",
                to="djangoapi.journalentry",
            ),
        ),
    ]
