# Generated by Django 5.2.12 on 2026-04-15 18:48

import backend.djangoapi.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0021_payout_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.djangoapi.utils.helpers.upload_to,
            ),
        ),
    ]
