# Generated by Django 5.2.12 on 2026-04-15 20:37

import backend.djangoapi.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0022_alter_journalentry_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.djangoapi.utils.helpers.journal_entries_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="tradingaccounttemplate",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=backend.djangoapi.utils.helpers.trading_account_templates_upload_to,
            ),
        ),
    ]
