# Generated by Django 5.2.12 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0024_journalentry_eval_contracts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="contracts",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="outcome",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="risk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
