# Generated by Django 5.2.12 on 2026-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0025_alter_journalentry_contracts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccount",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
