# Generated by Django 5.2.12 on 2026-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapi", "0026_tradingaccount_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="conversion_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="conversion_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="USD -> preferred_currency rate",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
