STRATEGY_TAG_MAP = {
    "ICT/SMC": [
        "HTF bias",
        "PD array",
        "premium",
        "discount",
        "EQ",
        "50% tap",
        "BOS",
        "CHOCH",
        "MSS",
        "internal BOS",
        "external BOS",
        "liquidity sweep",
        "BSL taken",
        "SSL taken",
        "EQH",
        "EQL",
        "inducement",
        "FVG",
        "FVG fill",
        "IFVG",
        "IFVG flip",
        "displacement",
        "OB",
        "MB",
        "BB",
        "breaker",
        "rejection block",
        "bullish SMT",
        "bearish SMT",
        "OTE",
        "OTE zone",
        "deep retracement",
        "1H High",
        "1H Low",
        "4H High",
        "4H Low",
        "PDH",
        "PDL",
        "Asia High",
        "Asia Low",
        "London High",
        "London Low",
        "NY High",
        "NY Low",
        "NYAM",
        "NYPM",
        "HOD",
        "LOD",
        "session sweep",
        "LTF confirmation",
        "clean structure",
        "high confluence",
        "momentum shift",
        "rejection wick",
    ],
    "AMD Model": [
        "accumulation",
        "manipulation",
        "distribution",
        "AMD complete",
        "liquidity sweep",
        "session sweep",
        "PDH",
        "PDL",
        "range deviation",
        "inducement",
        "false breakout",
        "stop hunt",
        "EQH",
        "EQL",
        "momentum shift",
        "displacement",
        "LO",
        "NYO",
    ],
    "Session-Based Trading": [
        "LO",
        "NYO",
        "killzone",
        "session sweep",
        "PDH",
        "PDL",
        "liquidity sweep",
        "range deviation",
        "accumulation",
        "manipulation",
        "distribution",
        "volatility expansion",
        "breakout",
        "reversal",
        "momentum strong",
        "momentum weak",
    ],
    "Support & Resistance": [
        "S/R flip",
        "key level",
        "PDH",
        "PDL",
        "EQH",
        "EQL",
        "rejection wick",
        "engulfing",
        "range deviation",
        "breakout",
        "retest",
        "fake breakout",
        "consolidation",
        "support hold",
        "resistance hold",
        "momentum shift",
    ],
    "Trendline Trading": [
        "TL touch",
        "TL break",
        "TL liquidity",
        "liquidity sweep",
        "breakout",
        "retest",
        "fake breakout",
        "confluence",
        "channel touch",
        "trend continuation",
        "trend reversal",
        "momentum shift",
        "rejection wick",
        "engulfing",
    ],
    "Orderflow": [
        "orderflow shift",
        "delta divergence",
        "volume spike",
        "absorption",
        "momentum strong",
        "momentum weak",
        "displacement",
        "imbalance",
        "aggressive buying",
        "aggressive selling",
        "bid/ask imbalance",
        "exhaustion",
        "continuation",
        "reversal",
        "volume confirmation",
    ],
    "VWAP/Mean Reversion": [
        "VWAP reclaim",
        "VWAP rejection",
        "VWAP deviation",
        "std dev 1",
        "std dev 2",
        "std dev 3",
        "range deviation",
        "mean reversion",
        "overextension",
        "snap back",
        "reversion to mean",
        "deviation expansion",
        "equilibrium return",
        "momentum weak",
        "exhaustion",
    ],
    "RSI/Indicator-Based": [
        "RSI divergence",
        "RSI OB",
        "RSI OS",
        "momentum shift",
        "hidden divergence",
        "trend continuation",
        "trend reversal",
        "overbought",
        "oversold",
        "indicator confluence",
        "momentum exhaustion",
        "signal crossover",
        "confirmation",
        "range trading",
    ],
    "Price Action": [
        "rejection wick",
        "engulfing",
        "momentum shift",
        "V-shape recovery",
        "PDH",
        "PDL",
        "EQH",
        "EQL",
        "breakout",
        "retest",
        "fake breakout",
        "inside bar",
        "outside bar",
        "pin bar",
        "consolidation",
        "range deviation",
        "trend continuation",
    ],
}

STRATEGIES = list(STRATEGY_TAG_MAP.keys())
